version: '3'
services:
 angular:
	image: angular-app
    	restart: always
    	build:
      	   websocket_angular/
    	container_name: angular-docker
    	network_mode: host
    	ports:
      	   - 4200:4200
 spring:
	image: spring-boot
    	restart: always
    	build:
      	   websocket_springBoot/
    	container_name: spring-docker1
    	network_mode: host
    	ports:
      	   - 8080:8080
	depends_on:
	   - angular











